### ISSUE TITLE
Create configurations to index content from Weld and CDI sitemaps

### ISSUE THREAD

**Issue by lukas-vlcek** [searchisko/configuration#32]
- Weld: http://weld.cdi-spec.org/sitemap.xml
- CDI: http://cdi-spec.org/sitemap.xml
- Weld documentation: http://docs.jboss.org/weld/reference/latest/en-US/html/sitemap.xml
  new global content type must be defined for the documentation as this is first time we index documentation

**Comment by velias** [comment]
Look https://issues.jboss.org/browse/ORG-2763 for the detailed tracking of the issue

**Comment by velias** [comment]
Deployed to the dcp2.jboss.org
