### ISSUE TITLE
Query for specific fields

### ISSUE THREAD

**Issue by wesbos** [searchisko/configuration#39]
Hey @lukas-vlcek - wondering how I can query by a specific field.

For example, I want to search for videos where the `_id` field is `jbossdeveloper_youtube-YoC0vDIWpC8` 

I'm not sure this is possible - is it? 

CC @paulrobinson - this is for the video detail page

**Comment by lukas-vlcek** [comment]
Hey @wesbos the query API is quite flexible. If I understand correctly you are working on Video detail page, so if you provide list of fields that are needed then a new registered query can be easily created specifically for this purpose or we can check if any of existing queries can be already (re)used. Is there any related JIRA ticket containing more details?

**Comment by wesbos** [comment]
The ticket is  RHD-1267 - we need all the fields

**Comment by lukas-vlcek** [comment]
OK, I will check this tomorrow. Please ping me if I forgot.

**Comment by unibrew** [comment]
I think we can close it as the referred RHD-1267 ticket is also closed. In case I'm wrong, please reopen.
