### ISSUE TITLE
Add all params to registered queries

### ISSUE THREAD

**Issue by wesbos** [searchisko/configuration#49]
I'm trying to use the date queries via this url:

http://dcp.stage.jboss.org/v2/rest/search/developer_materials?activity_date_from=2016-03-17T04:00:00.000Z&activity_date_to=2016-03-31T04:00:00.000Z

but it returns the same data without it:

http://dcp.stage.jboss.org/v2/rest/search/developer_materials

And the same for activity_date_interval:

http://dcp.stage.jboss.org/v2/rest/search/developer_materials?activity_date_interval=week

Can we get these queries added for registered queries too?

**Comment by unibrew** [comment]
Developer materials query does not have such parameters defined at the moment https://github.com/searchisko/configuration/blob/master/data/query/developer_materials.md

**Comment by lukas-vlcek** [comment]
@unibrew I asked Wes to open this ticket. We need to get more details and check if it is possible to add support for required parameters.

**Comment by lukas-vlcek** [comment]
@unibrew Do you want to look at this?

**Comment by unibrew** [comment]
Well I have some other important tasks at the moment. In Wes' team is Dan who can handle this at least from technical perspective, not sure about his time and priorities.

**Comment by wesbos** [comment]
@unibrew @lukas-vlcek So this is a no? How would I handle the date filtering dynamically then?

**Comment by lukas-vlcek** [comment]
@wesbos I will take a look tomorrow. Please ping me if I forgot. Thanks.

**Comment by wesbos** [comment]
@lukas-vlcek ping!

**Comment by lukas-vlcek** [comment]
@wesbos pong, I guess this is still pending request, correct? Let me know if not, otherwise I am adding this to my pipeline for this week.

**Comment by lukas-vlcek** [comment]
@wesbos can you please remind me what are the missing URL parameters you need? Do you need more than `activity_date_from` and `activity_date_to`?

**Comment by lukas-vlcek** [comment]
@wesbos I added both `activity_date_from` and `activity_date_to` URL params to `developer_materials` query.

You can test it on staging:
- [dcp.stage...&activity_date_from=2011-12-06T06:34:55.000Z](https://dcp.stage.jboss.org/v2/rest/search/developer_materials?query=java+tutorial&activity_date_from=2011-12-06T06:34:55.000Z)
- [dcp.stage...&activity_date_to=2011-12-06T06:34:55.000Z](https://dcp.stage.jboss.org/v2/rest/search/developer_materials?query=java+tutorial&activity_date_to=2011-12-06T06:34:55.000Z)

Also updated documentation in branch #49. See:
- [activity_date_from](https://github.com/searchisko/configuration/blob/49/data/query/developer_materials.md#activity_date_from)
- [activity_date_to](https://github.com/searchisko/configuration/blob/49/data/query/developer_materials.md#activity_date_to)

Please let me know if you have any questions.

**Comment by wesbos** [comment]
This seems to be working! Thanks so much - I really appreciate it!

**Comment by lukas-vlcek** [comment]
@wesbos if this is what you want to use then please reopen this ticket and I will work with the rest of the team to push this update to master and relevant Searchisko instances.

**Comment by wesbos** [comment]
@lukas-vlcek Sorry I didn't see this. 

This is what I want, but we also need `activity_date_interval` to work as well. Can we do that?

**Comment by unibrew** [comment]
I believe we handled all the requirements and the new site already uses developer_materials query.
